### PR TITLE
feat: restore test-elixir

### PR DESCRIPTION
**Pull request by vitalis**
### 🤔 What's changed?

Restore Elixir tests for CI with correct OTP / Elixir versions

### 🏷️ What kind of change is this?

- :bank: Refactoring/debt/DX (improvement to code design, tooling, etc. without 

### 📋 Checklist:

- [x] I agree to respect and uphold the [Cucumber Community Code of Conduct](https://github.com/cucumber/.github/tree/main?tab=coc-ov-file)

----

### CODE REVIEW

**Comment by mpkorstanje** [comment]
Cheers much appreciated!

**Comment by vitalis** [comment]
With ❤️  
You did most of the work :)
@mpkorstanje, if you have more Elixir related tickets, just assign them to me ;)

**Comment by luke-hill** [comment]
Hi @vitalis if you're available to can you join us on discord if you're wanting to support more with the elixir work that is required?

Invite for discord is here: https://discord.gg/Yw8YCM9z

**Comment by vitalis** [comment]
> Hi @vitalis if you're available to can you join us on discord if you're wanting to support more with the elixir work that is required?
> 
> Invite for discord is here: https://discord.gg/Yw8YCM9z

Hi, I'm in :) What should I do next? :)

**Pull request merged**
