### PR TITLE
Incomplete scenarios

### PR DESCRIPTION
**Pull request by enkessler**
The scenario equivalent of #160. Adding test data in order to ensure that we allow incomplete scenarios and also ensure to not make pickles out of them.

.Net and Go didn't break for some reason.

- [ ] <s>.Net</s> (compiler not made #131)
- [ ] <s>Go</s> (compiler not made #129)
- [x] Java
- [x] JavaScript
- [ ] <s>Objective-C</s> (compiler not made #130)
- [x] Perl
- [x] Python
- [x] Ruby

### CODE REVIEW

**Comment by aslakhellesoy** [comment]
Thanks @enkessler this looks good

**Comment by aslakhellesoy** [comment]
Others - feel free to push to same branch if you have karma

**Comment by enkessler** [comment]
Because not pickling stepless scenarios is different from the previous behavior, shouldn't the Go and .Net versions have started to fail the tests?

**Comment by aslakhellesoy** [comment]
@enkessler the compiler isn't implemented on all platforms yet: #129 #130 #131

**Pull request merged**
