### PR TITLE
go: upgrade messages to v22

### PR DESCRIPTION
**Pull request by dolmen**
Upgrade `github.com/cucumber/messages/go` from `v21` to `v22`.

### 🤔 What's changed?

* Change import in dialects_builtin.go.jq
* Regenerate dialects_builtin.go
* Change imports in other *.go.
* `go mod tidy` to remove references to `v21` and its dependencies

The changes were fully automated from CLI (note that those commands could be used to add a target in the Makefile):
```console
$ cd go
$ sed -i '' 's!github.com/cucumber/messages/go/v21!github.com/cucumber/messages/go/v22!' dialects_builtin.go.jq
$ make dialects_builtin.go
$ sed -i '' 's!"github.com/cucumber/messages/go/v21"!"github.com/cucumber/messages/go/v22"!' *.go main/*.go
$ go mod tidy
```

### ⚡️ What's your motivation? 

The renovate bot does a bad job. It doesn't update version references in Go sources. We can't trust it for Go.

### 🏷️ What kind of change is this?

- :bank: Refactoring/debt/DX (improvement to code design, tooling, documentation etc. without changing behaviour)

### ♻️ Anything particular you want feedback on?

No.

### 📋 Checklist:

- [x] I agree to respect and uphold the [Cucumber Community Code of Conduct](https://cucumber.io/conduct/)

### CODE REVIEW

**Comment by dolmen** [comment]
Cc: @krichprollsch

**Review by mpkorstanje — CHANGES_REQUESTED** [review]
Please do add an entry to the changelog.

**Comment by dolmen** [comment]
@mpkorstanje 
1. Rebased (with conflict resolved)
2. CHANGELOG entry added

**Comment by dolmen** [comment]
Ping @mpkorstanje

**Review by mpkorstanje — APPROVED** [review]

**Comment by mpkorstanje** [comment]
Cheers!

**Pull request merged**
