### PR TITLE
[.NET] Adopt c# 12 primary constructors

### PR DESCRIPTION
**Pull request by Romfos**
### 🤔 What's changed?

- Adopt c# 12 primary constructors
documentation: https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/primary-constructors
- Remove some unsued private settters

### ⚡️ What's your motivation? 

Adopt modern c# language feature to simplify code base

### 🏷️ What kind of change is this?

- :bank: Refactoring/debt/DX (improvement to code design, tooling, etc. without changing behaviour)

### ♻️ Anything particular you want feedback on?

no changes in product. code style changes only

### 📋 Checklist:

- [x] I agree to respect and uphold the [Cucumber Community Code of Conduct](https://github.com/cucumber/.github/tree/main?tab=coc-ov-file)
- [ ] I've changed the behaviour of the code
  - [ ] I have added/updated tests to cover my changes.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly.
- [ ] Users should know about my change
  - [x] I have added an entry to the "Unreleased" section of the [**CHANGELOG**](../blob/main/CHANGELOG.md), linking to this pull request.

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/PULL_REQUEST_TEMPLATE.md)*

### CODE REVIEW

**Comment by luke-hill** [comment]
@Romfos - Given the breaking changes that have already gone in for .NET does it make sense to get these in too so there's just one large changeset for .NET as the next version (v30)? Or should this go in as a separate change?

**Comment by Romfos** [comment]
@luke-hill As you wish.
I'm planning to create several next PR's after this.
This is not a blocker for release. You can release it any time at current state or wait full change set.
After ever PR all test are green and lib is ready for release

**Comment by luke-hill** [comment]
@Romfos - What I meant is if you're doing a few breaking changes for .NET it makes sense to get them all in one go as the major version will change for all flavours of gherkin

Given the next version is already a major, any / all new breaking changes you can get in soon makes it easier for us

**Comment by Romfos** [comment]
@luke-hill  got it. Some low impactful but breaking changes are expected

Please assist me me with code review

**Review by mpkorstanje — APPROVED** [review]
Looks good. I'll merge this probably tomorrow.

@luke-hill while it's good to bundle big but non-breaking changes, it is not essential. With half a dozen languages in one project we'll always have a few people working in parallel. That will create some contention. So it is better to have regular releases to keep the momentum.

Breaking changes however are good to group together.

**Comment by mpkorstanje** [comment]
@Romfos my and other maintainers availability is intermittent. And for some changes we'll have to reach out to people with more .Net knowledge. This makes the process a bit slow. Especially with the current batch size.

So far your changes have been well defined, narrowly scoped and non-breaking. And it looks like you are doing general maintenance so I assume there will be more like it.

Would you be okay with bundeling all future changes that meet these criteria as a single PR with each commit being a what is now a PR?

Should we find anything controversial we can merge the non controversial commits and work out the problematic parts separately.

**Comment by Romfos** [comment]
@mpkorstanje okay. I will do it for the next PR

**Pull request merged**
