### PR TITLE
Further tidy ups after migrating from py2 to just py3

### PR DESCRIPTION
**Pull request by jsa34**
Trying to restore windows after having encoding issues.

### 🤔 What's changed?

Reinstate Windows tests and fix test issues.
Last tidy ups of legacy py2 code.

### 🏷️ What kind of change is this?

- :book: Documentation (improvements without changing code)
- :bank: Refactoring/debt/DX (improvement to code design, tooling, etc. without changing behaviour)
- :bug: Bug fix (non-breaking change which fixes a defect)
- :zap: New feature (non-breaking change which adds new behaviour)
- :boom: Breaking change (incompatible changes to the API)

### 📋 Checklist:

- [x] I agree to respect and uphold the [Cucumber Community Code of Conduct](https://github.com/cucumber/.github/tree/main?tab=coc-ov-file)
- [ ] I've changed the behaviour of the code
  - [ ] I have added/updated tests to cover my changes.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly.
- [ ] Users should know about my change
  - [ ] I have added an entry to the "Unreleased" section of the [**CHANGELOG**](../blob/main/CHANGELOG.md), linking to this pull request.

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/PULL_REQUEST_TEMPLATE.md)*

### CODE REVIEW

**Review by youtux — APPROVED** [review]
I think we should merge this, and fix the Windows error in a separate PR

**Comment by jsa34** [comment]
Sure - I will refocus the description and rebase after your black linting if that's ok?

**Comment by youtux** [comment]
👍

**Comment by jsa34** [comment]
Rebasing went messy, so just manually did again and will raise a new PR

**Pull request closed without merging**
