### PR TITLE
Fix compilation issues with clang

### LINKED ISSUE #191: [gherkin-cpp] does not work/compile with clang-cl//MSVC
### 👓 What did you see?
Tried to compile for windows, using clang-cl and MSVC. Does not work, there are missing includes, incorrect includes, clang/gcc-only includes, incorrect template syntax etc.

### ✅ What did you expect to see?
A working build

### 📦 Which tool/library version are you using?
gherkin-cpp, current (first released).
clang-cl 15, clang-cl 16, MSVC 2019

### 🔬 How could we reproduce it?
I'll provide an example repo if this is being picked up

1. Install '...' version '...'
2. Create a file called '....'
3. Run command '....'
4. See error '....'

### 📚 Any additional context?
Not much
----
 
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/bug_report.md)*

### LINKED ISSUE #192: [gherkin-cpp, messages-cpp] unable to use Cmake FetchContent to include gherkin-cpp as-source.
### 👓 What did you see?

It is currently not possible to use CMake's FetchContent to include gherkin-cpp and messages-cpp within a project. Both projects are currently setup with a Linux workflow in mind. 'Compile library separately, install library separately, use CMake 'Find' to include the pre-build binary.
This is however not the only way of using CMake projects. Often times it is useful to include the library directly as a dependency, and build the library while building the rest of the project. This especially useful for single-stage builds, instead of multi-stage builds.

### ✅ What did you expect to see?

Being able to FetchContent() gherkin-cpp

### 📦 Which tool/library version are you using?

cmake version 3.27.7

### 🔬 How could we reproduce it?

Will provide an example repository when this is picked up

1. Install '...' version '...'
2. Create a file called '....'
3. Run command '....'
4. See error '....'

### 📚 Any additional context?

I am building a cucumber runner using cpp. Where gherkin-cpp is the backend for parsing the gherkin files and providing me with a nice json object. The cucumber runner will be made open source (MIT licensed)

----
 
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/bug_report.md)*

### PR DESCRIPTION
**Pull request by daantimmer**
### 🤔 What's changed?

- modified cmake files in order to be used with FetchContent. No more assumption that the project will always be the root project
- reworked template code for is_container_v, does not work with clang-cl//MSVC. Made more explicit and more standard compliant
- removed demangle.hpp/cpp, dead code and does not work with clang-cl/MSVC
- fixed the `full_match` regex function as there was a mismatch between template parameters and actual parameters

### ⚡️ What's your motivation? 

- Fixes #191
- Fixes #192

### 🏷️ What kind of change is this?

- :bank: Refactoring/debt/DX (improvement to code design, tooling, documentation etc. without changing behaviour)
- :bug: Bug fix (non-breaking change which fixes a defect)

### ♻️ Anything particular you want feedback on?

- I tried to adhere to the already existing coding standard, but not sure if I did it right (there is, sadly, no accompanying clang-format file. Might be a nice todo item?)
- not sure if the template magic for detecing container type is to your liking

### 📋 Checklist:

- [x] I agree to respect and uphold the [Cucumber Community Code of Conduct](https://cucumber.io/conduct/)
- [x] Users should know about my change
  - [ ] I have added an entry to the "Unreleased" section of the [**CHANGELOG**](../blob/main/CHANGELOG.md), linking to this pull request.

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/PULL_REQUEST_TEMPLATE.md)*

### CODE REVIEW

**Comment by chybz** [comment]
Hey there, been working on those fixes for some time now. That might not be aligned with your schedule but those issues are being resolved real soon now, albeit sometimes differently.

**Comment by daantimmer** [comment]
No problem. Take your time. In the mean time we will just use our fork with the required fixes.

**Comment by daantimmer** [comment]
My colleague, who just pushed an update to our fork, uses MSVC and visual studio btw.

**Comment by chybz** [comment]
@daantimmer @richardapeters Could you please test with `main` branch and report any problem back to me ? Thank you.

**Comment by daantimmer** [comment]
> @daantimmer @richardapeters Could you please test with `main` branch and report any problem back to me ? Thank you.

-> https://github.com/philips-software/amp-cucumber-cpp-runner/pull/22

**Comment by chybz** [comment]
@daantimmer @richardapeters Thank you very much for reporting the issues and help me resolve them, greatly appreciated !
Had to make other adjustments beyond just compile fixes, hope you understand why I've not merged this PR.
Unless there are other topics, do we all agree to close this PR and the other one on cucumber/messages ?

**Comment by daantimmer** [comment]
@chybz the PRs and issues may be closed as resolved.

Thank you for your time as well. This library is hugely appreciated and have given us the opportunity to create the open source runner in such a short time.

**Pull request closed without merging**
