### PR TITLE
Add Business Need and Ability to pt language

### PR DESCRIPTION
**Pull request by praticandobdd**
### 🤔 What's changed?

According to Writing Great Specifications book it's a option describe user needs and abilities instead of features in a feature file

### ⚡️ What's your motivation? 

For me e for my team that approach makes sense

### 🏷️ What kind of change is this?

Add new keywords to pt language 

- :zap: New feature (non-breaking change which adds new behaviour)

### ♻️ Anything particular you want feedback on?

-

### 📋 Checklist:

-
- [x] I agree to respect and uphold the [Cucumber Community Code of Conduct](https://cucumber.io/conduct/)
- [ ] I've changed the behaviour of the code
  - [ ] I have added/updated tests to cover my changes.
- [x] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly.
- [x] Users should know about my change
  - [ ] I have added an entry to the "Unreleased" section of the [**CHANGELOG**](../CHANGELOG.md), linking to this pull request.

### CODE REVIEW

**Comment by mpkorstanje** [comment]
Cheers!

Can you follow the instructions here https://github.com/cucumber/gherkin/blob/main/CONTRIBUTING.md#adding-or-updating-an-i18n-language

And please also update the changelog.

**Comment by praticandobdd** [comment]
@mpkorstanje  thanks for your orientation . I'll fix my merge request as soon as possible

**Comment by tulavalle** [comment]
This contribution is very important because it makes it possible to work closer to specification literature, such as the one cited by the author of the PR, that is, it makes it possible not only to describe resources, but also to document in order to make it clear that the documentation is not just about of functionality but rather of user needs and skills, leaving these intentions explicit in the documentation writing, allowing a documentation process based on BDD, much more robust and flexible for the needs of different contexts

**Comment by mpkorstanje** [comment]
I'm closing this due to inactivity. If some one wants to add this in the future, please do feel free to create a new pull request.

**Pull request closed without merging**
