### PR TITLE
complier: pickle keyword

### PR DESCRIPTION
**Pull request by charlierudolph**
@aslakhellesoy 

Got gherkin3 and the compiler working for cucumber-js (all the feature tests passing). 
Just doing some unit test cleanup at the moment. 
My cucumber-js branch is dependent on my own branch of gherkin-javascript.
This PR implements the changes I need.

### CODE REVIEW

**Comment by aslakhellesoy** [comment]
Great stuff @charlierudolph.

Can you update the implementations that are failing on Travis please?

**Comment by aslakhellesoy** [comment]
@charlierudolph can you explain _why_ cucumber-js needs this? Is it for snippets? Did you see @brasmusson's suggestion in https://github.com/cucumber/gherkin3/issues/109#issuecomment-147807301 ?

**Comment by charlierudolph** [comment]
Currently it is used for both the snippets and the pretty formatter.

Without the keyword, the pretty formatter would become much more complex. I'm fine renaming to `snippet_keyword` though then it becomes inconsistent with scenarios where I moved keyword to its own key.

**Comment by charlierudolph** [comment]
@aslakhellesoy any more thoughts? The cucumber-js PR is now blocking on this.

**Comment by aslakhellesoy** [comment]
I'm a little snowed under now and about to disappear for 6 weeks. I need some more time to consider this - sorry.

**Comment by charlierudolph** [comment]
I'm fine leaving this out if we want to move the pretty formatter to not printing out the keywords anymore. The snippets don't necessarily need the keyword either.

**Comment by aslakhellesoy** [comment]
The pretty formatter doesn't need the keyword in order to print the keyword ;-). I'll release some code as soon as I can to demonstrate how (microcuke - a cucumber implementation in 500 SLOC).

We might add a `snippet_keyword` property to be used exclusively for snippet generation.

**Comment by charlierudolph** [comment]
microcuke doesn't handle scenario outlines which is one example where the pretty formatter can't just print the source.

**Comment by aslakhellesoy** [comment]
You're right that it doesn't currently handle scenario outlines. That's not to say it's not possible to make it do so though.

I'm aware that making cucumber only aware of pickles complicates pretty printing, but it considerably simplifies execution logic and the ability to swap in other formats such as Markdown.

We'll get there - we just have to experiment a little more.

**Comment by charlierudolph** [comment]
What do you think about simplifying pretty printing to not have the keyword? I don't think it adds anything.

**Comment by brasmusson** [comment]
Performing the steps: parse feature file (to ast) -> compile (to pickles) -> make to test cases -> execute -> ...
is not just dividing the computation into a pipeline of steps. The abstraction level is also changed along the pipeline. The compilation move from a feature(/source) abstraction to a pickle abstraction. The latter makes the execution of test cases simpler, but it does not have all the information for doing feature(/source) level reporting of the result.

Feature(/source) level reporting requires the use of both the feature(/source) file and the result (file), whereas test case level reporting only requires the result (file). In the end we want to be able to perform (some) feature(/source) level reporting - a HTML-formatter is an example of where feature(/source) level reporting is wanted.

The pretty formatter is very much doing feature(/source) level reporting (judging from Cucumber-Ruby), it practically pretty prints the feature file with colour annotations about the results. The progress formatter on other hand is doing test case level reporting (I as see it).

Maybe we should introduce a console formatter in between the progress formatter and the pretty formatter (which would still do feature/source level reporting), a console formatter that prints the test cases and steps executed, but only on test case level - so it does only have to use data that exist in the pickles?

**Comment by charlierudolph** [comment]
I think we should actually move away from print the source. The formatters should really only be printing whats running and as long as we give the link back to the source it should be good. I would like a pretty formatter that looks like:

source
```cucumber
Feature: some feature
  Scenario: test case A
    Given step 1
    When step 2
    Then step 3
  
  Scenario Outline: test case B
     Given step <LETTER>
     When step tango
     Then step zulu

    Examples: 
       | LETTER |
       | alpha |
       | omega |
```

Output
```
some feature 

  test case A # features/a.feature:2 
    step 1
    step 2
    step 3

  test case B # features/a.feature:14
    step alpha
    step tango
    step zulu

  test case B # features/a.feature:15 
    step omega
    step tango
    step zulu
````
The steps can be colored as always.

**Comment by aslakhellesoy** [comment]
I think that's a great idea. If we omit the feature header, this might even print scenarios that are run in random order.

**Comment by brasmusson** [comment]
I don't know why the pretty formatter original was name pretty formatter, but the association I get is it pretty prints the feature (source) file - annotated with results - therefore it is named *pretty* formatter. Maybe a console formatter which works on test case level instead of source level should be named something else?

With respect to discussions about the [parallel_tests gem](https://github.com/cucumber/cucumber-ruby/issues/924), I have been thinking that in such settings, you maybe only want the test case (and not the steps) - with their results - printed on the console.

**Comment by charlierudolph** [comment]
Closing, agree with the reasons for not having it, grabbing the keyword by parsing the AST.

**Pull request closed without merging**
