### PR TITLE
C++ implementation

### PR DESCRIPTION
**Pull request by chybz**
### 🤔 What's changed?

- Added C++ implementation

### ⚡️ What's your motivation? 

- Add native support for C++ 

### 🏷️ What kind of change is this?

- :zap: New feature (non-breaking change which adds new behaviour)

### ♻️ Anything particular you want feedback on?

- was unable to check CI/CD behavior
- 
### 📋 Checklist:

- [x] I agree to respect and uphold the [Cucumber Community Code of Conduct](https://cucumber.io/conduct/)

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/PULL_REQUEST_TEMPLATE.md)*

### CODE REVIEW

**Comment by mpkorstanje** [comment]
If I've not done it wrong, you should now be able to push and that will trigger CI.

**Comment by TheKayneGame** [comment]
Any Updates Regarding this PR?

**Comment by chybz** [comment]
@TheKayneGame apart from the minor conflicts in the two Markdown files that occurred recently, I couldn't merge this PR about 4 months ago when @mpkorstanje kindly gave me access (I also worked on the [messages](https://github.com/cucumber/messages) C++ implementation).
Could you please tell me what's missing ?

**Comment by TheKayneGame** [comment]
@chybz First of all thanks for the hard work.
The reason i ask this question is because this PR seems to have been open for all this time. and i was afraid it might have gone stale of something.

My main question is: Will this PR ever be merged?

**Comment by chybz** [comment]
That is indeed my only goal atm. Last time I tried, I was not allowed to do so.
I'll fix the small conflicts today and give it another go and keep you informed.

**Comment by TheKayneGame** [comment]
Why has this been closed now?

**Comment by chybz** [comment]
I erroneously rebase a wrong local branch in my repo.
I trashed all of it, and restarted from scratch on another (now merged) PR.

Sorry for all that noise.

**Pull request closed without merging**
