### PR TITLE
Allow incomplete scenario outlines

### PR DESCRIPTION
**Pull request by brasmusson**
This PR change the Gherkin parser to not consider an incomplete scenario outline an error. This fixes one aspect of #153.

- [x] .NET
- [x] Go
- [x] Java
- [x] Javascript
- [x] Objective-C
- [x] Perl
- [X] Python
- [x] Ruby

### CODE REVIEW

**Comment by enkessler** [comment]
Nice job tackling the thing that has the most use cases first!

The only other case that I can think of that I don't see in your commit is an outline with steps but not an example block.

    Scenario Outline: only steps
      * a step

**Comment by aslakhellesoy** [comment]
This looks good to me - let's go ahead and implement it for all platforms!

**Comment by aslakhellesoy** [comment]
Getting there!

**Comment by brasmusson** [comment]
@aslakhellesoy I got `ERROR: Permission to cucumber/gherkin-perl.git denied` when pushing subtrees after having merged this PR. It seems like the access rights for the repository cucumber/gherkin-perl is not setup as expected.

**Comment by aslakhellesoy** [comment]
Try again?

**Comment by brasmusson** [comment]
Now it worked, thanks.

**Comment by aslakhellesoy** [comment]
That is a phenomenal job @brasmusson. Thanks!!

**Comment by SabotageAndi** [comment]
Any plan when a version with this PR is on NuGet.org?

**Comment by aslakhellesoy** [comment]
@SabotageAndi we don't provide estimates, but you can look at the [CHANGELOG](https://github.com/cucumber/gherkin/blob/master/CHANGELOG.md) to get an idea of how frequently we have made releases in the past.

**Pull request merged**
