### PR TITLE
fix: Avoid deprecation warnings in CMakeLists.txt by requiring minimum version 3.5

### PR DESCRIPTION
**Pull request by simonhyll**
### 🤔 What's changed?

CMake below 3.5 is going to be deprecated. Setting the minimum version to 3.5 suppresses that annoying warning. Also, the minimum version should be set before the project, otherwise you also get an annoying warning about that.

### ⚡️ What's your motivation? 

Warnings are annoying when they're this simple to fix.

### 🏷️ What kind of change is this?

- :bug: Bug fix (non-breaking change which fixes a defect)

### 📋 Checklist:

- [x] I agree to respect and uphold the [Cucumber Community Code of Conduct](https://github.com/cucumber/.github/tree/main?tab=coc-ov-file)
- [ ] I've changed the behaviour of the code
  - [ ] I have added/updated tests to cover my changes.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly.
- [ ] Users should know about my change
  - [ ] I have added an entry to the "Unreleased" section of the [**CHANGELOG**](../blob/main/CHANGELOG.md), linking to this pull request.

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/PULL_REQUEST_TEMPLATE.md)*

### CODE REVIEW

**Comment by luke-hill** [comment]
I don't know enough about c to make an informed decision on this. But do you think this should be communicated in changelog @simonhyll 

Also is this a runtime change? If so should it go into a minor release? Or is this something that would have to be considered a breaking change.

@ursfassler are you still taking an interest in the c project?

**Comment by ursfassler** [comment]
@luke-hill I am interested in having a working C/C++ cucumber implementation, but didn't knew/monitor this c code (I am on https://github.com/cucumber/cucumber-cpp/)
As I didn't had much time for it to, I am not up to date of the plans for the cucumber C/C++ implementation.

**Comment by ursfassler** [comment]
CMake 3.5 seems already ancient.
The change should not have an impact on the code, but it could break a build (i.e. may need some manual changes to fix the build).

**Comment by luke-hill** [comment]
I'll wait to merge until you have more understanding and agree this is the way forward. As the next release is just going to be 30.0.1

**Comment by mpkorstanje** [comment]
So given that we currently don't have a dedicated maintainer for C and given that we do have a pull request that solve a problem for someone using Gherkin C, I think we can merge this.

**Pull request merged**
