### PR TITLE
Georgian language

### PR DESCRIPTION
**Pull request by dobiedad**
Added support for the Georgian language. 
All words are translated exactly apart from "background" which i translated into context .

### CODE REVIEW

**Comment by aslakhellesoy** [comment]
დიდი მადლობა @dobiedad! Will merge this into the next release :-)

**Comment by aslakhellesoy** [comment]
You even updated the language files - good patch!

**Comment by dobiedad** [comment]
The perl file was a pain!

**Comment by dobiedad** [comment]
@brasmusson I manually updated `gherkin-languages.json`and ran the make task but perl kept on failing. The issue was it expected the JSON module to be in a folder called `Cpanel` and for some reason mine was at the root not in that folder.

**Pull request merged**
